version: '3.9'

services:
  web:
    build: .
    container_name: loteria-apache
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=secret
      - DB_NAME=juego

  db:
    image: mariadb:10.11
    container_name: loteria-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: juego
    volumes:
      - ./juego.sql:/docker-entrypoint-initdb.d/juego.sql
      - db_data:/var/lib/mysql
    ports:
      - "3307:3307"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: loteria-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: secret
    depends_on:
      - db

volumes:
  db_data:
